apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.35.0 (HEAD)
  labels:
    io.kompose.service: flask-app
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: flask-app
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.35.0 (HEAD)
      labels:
        io.kompose.service: flask-app
    spec:
      containers:
        - env:
            - name: FLASK_APP
              value: app/app.py
            - name: FLASK_ENV
              value: "development"
            - name: SQLALCHEMY_DATABASE_URI
              value: "mysql+pymysql://user:user_password@mysql:3306/tasks_db"
          image: gcr.io/task-449116/flask-app:latest
          name: flask-app
          ports:
            - containerPort: 5000
              protocol: TCP
      restartPolicy: Always
